### PR TITLE
Remove data_bindings and use module hiera data

### LINKED ISSUE #11: Support for Puppet 4.9.x
Looks like classifier is broken on Puppet 4.9.x.

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not autoload /puppet/data_providers/classifier_data_provider_factory: uninitialized constant Puppet::DataProvider
````

### PR DESCRIPTION
**Pull request by vinzent**
Makes it compatible with Puppet 4.10.5 and Puppet 5.0.1 because of [PUP-7751](https://tickets.puppetlabs.com/browse/PUP-7751)

Resolves #11

### CODE REVIEW

**Comment by vinzent** [comment]
PUP-7751 PR: https://github.com/puppetlabs/puppet/pull/6038

**Comment by ripienaar** [comment]
Can we update the README to say the previously experimental feature has been removed?

https://github.com/ripienaar/puppet-classifier#exposing-data-to-hiera

**Comment by ggeldenhuis** [comment]
Would be useful for puppet 5.x to get this change merged as currently the module does not work out of the box on puppet 5.3.2 specifically.

**Comment by ripienaar** [comment]
👍 @ggeldenhuis do you want to PR the removal of the whole section `Exposing Data to Hiera` in a followup?

**Comment by ggeldenhuis** [comment]
@ripienaar done

**Pull request merged**
