### PR TITLE
Fixes for 'in' operator

### PR DESCRIPTION
**Pull request by m4ce**
1) fixed missing closing curly bracket
2) fixed logic with 'in' operator whereby right (value) should be in left (fact)

### CODE REVIEW

**Comment by ripienaar** [comment]
thanks, I should stop being lazy and set up some tests for this but when i wrote it rspec-puppet didnt even work with 4 yet :(

**Comment by ripienaar** [comment]
I am not sure we have the same ideas about what this does, can you give me an example for how you are using it?

For me I'd like to use it like this:

```yaml
"Foo Servers":
  rules:
    - fact: "%{facts.hostname}"
      operator: "in"
      value:
        - "foo1"
        - "foo2"
        - "other1"
  classes:
    - "roles::fooserver"
```

but with the right and left as you made it this wont work, how do you use it @m4ce ?

**Comment by m4ce** [comment]
Hi,

I use it for the following scenario:

```
  "Role: mysql slave":
    rules:
      - fact: "%{::roles}"
        operator: in
        value: "mysql_slave"
    classes:
      - "mysql::slave"
```

roles happens to be an Array.

**Comment by ripienaar** [comment]
hmm, this seems wrong way round then :) if you read it "if thing in other things" it makes sense, yours is saying "if other things in thing" which reads wrong :)

what do you think?

**Comment by m4ce** [comment]
The default behavior should be "if left in right" indeed.

However, that breaks if fact is an array and one wants to check if the value (right) is in the fact (left).

Perhaps if the fact (right) is an Array, we could turn the condition to be if right in left?

**Comment by ripienaar** [comment]
you cant do this?

```
 "Role: mysql slave":
    rules:
      - fact: "mysql_slave"
        operator: in
        value: "%{::roles}"
    classes:
      - "mysql::slave"
```

I suspect this will work, the word fact there is more a guide than a rule, its just random left and right data :) give it a try with the reversed logic?

**Comment by m4ce** [comment]
Right - that works too :)

No worries, go ahead pushing your changes. I will then pull the latest version down and adjust the logic accordingly.

Thanks!

**Comment by ripienaar** [comment]
awesome thanks :)

**Comment by ripienaar** [comment]
@m4ce ok, i reversed that in master, will release 'morrow

**Comment by m4ce** [comment]
Thank you!

**Pull request merged**
